### ISSUE TITLE
Failure strategy in Visualization

### ISSUE THREAD

**Issue by bjhardcastle** [AllenNeuralDynamics/aind-ephys-pipeline-kilosort25#14]
In this session probe E was not inserted, and it looks like spike sorting failed as a result - which is tolerated in the pipeline.

However, the Visualization capsule failed when attempting to make plots for probe E, which crashed the entire pipeline.

Perhaps the failure strategy could be adjusted on this capsule. 

--- 

https://codeocean.allenneuraldynamics.org/data-assets/53155b0b-ed46-4481-a9c4-4cbdb7f03a12/ecephys_706401_2024-04-25_12-03-03_sorted_2024-07-12_11-13-51
asset ID `53155b0b-ed46-4481-a9c4-4cbdb7f03a12`

sorting failure in `output`:
```
...
	SPIKE SORTING FAILED!
Error log:

{'datetime': '2024-07-11T22:24:31.700215',
 'error': True,
 'error_trace': 'Traceback (most recent call last):\n'
                '  File '
                '"/home/miniconda3/lib/python3.9/site-packages/spikeinterface/sorters/basesorter.py", '
                'line 258, in run_from_folder\n'
                '    SorterClass._run_from_folder(sorter_output_folder, '
                'sorter_params, verbose)\n'
                '  File '
                '"/home/miniconda3/lib/python3.9/site-packages/spikeinterface/sorters/external/kilosortbase.py", '
                'line 217, in _run_from_folder\n'
                '    raise Exception(f"{cls.sorter_name} returned a non-zero '
                'exit code")\n'
                'Exception: kilosort2_5 returned a non-zero exit code\n',
 'run_time': None,
 'runtime_trace': ['Warning: X does not support locale C.UTF-8',
                   'Time   0s. Computing whitening matrix..',
                   'Getting channel whitening matrix...',
                   'Channel-whitening matrix computed.',
                   'Time  59s. Loading raw data and applying filters...',
                   'Time 1618s. Finished preprocessing 3421 batches.',
                   'Drift correction ENABLED',
                   'pitch is 20 um',
                   '----------------------------------------Index in position '
                   '2 exceeds array bounds. Index must not exceed 3.'],
 'sorter_name': 'kilosort2_5',
 'sorter_version': 'compiled'}
...
```

ultimate error in output:
```
...
Command exit status:
  1

Command output:
  [capsule-6668112] cloning git repo...
  [capsule-6668112] running capsule...
  
  
  VISUALIZATION
  Session name: ecephys_706401_2024-04-25_12-03-03
  Visualizing recording: experiment1_Record Node 103#Neuropix-PXI-100.ProbeE-AP_recording1
  	Could not load waveform extractor or recording for experiment1_Record Node 103#Neuropix-PXI-100.ProbeE-AP_recording1
  	Visualizing drift maps using detected peaks (no spike sorting available)
  	Detected 0 peaks
  	Visualizing motion

Command error:
  [capsule-6668112] cloning git repo...
  Cloning into 'capsule-repo'...
  [capsule-6668112] running capsule...
  + python -u run_capsule.py
  VISUALIZATION
  Session name: ecephys_706401_2024-04-25_12-03-03
  Visualizing recording: experiment1_Record Node 103#Neuropix-PXI-100.ProbeE-AP_recording1
  	Could not load waveform extractor or recording for experiment1_Record Node 103#Neuropix-PXI-100.ProbeE-AP_recording1
  	Visualizing drift maps using detected peaks (no spike sorting available)
  	Detected 0 peaks
  	Visualizing motion
  Traceback (most recent call last):
    File "/tmp/nxf.oxhXkP75LI/capsule/code/run_capsule.py", line 275, in <module>
      w_motion = sw.plot_motion(
    File "/opt/conda/lib/python3.9/site-packages/spikeinterface/widgets/motion.py", line 65, in __init__
      BaseWidget.__init__(self, plot_data, backend=backend, **backend_kwargs)
    File "/opt/conda/lib/python3.9/site-packages/spikeinterface/widgets/base.py", line 82, in __init__
      self.do_plot()
    File "/opt/conda/lib/python3.9/site-packages/spikeinterface/widgets/base.py", line 103, in do_plot
      func(self.data_plot, **self.backend_kwargs)
    File "/opt/conda/lib/python3.9/site-packages/spikeinterface/widgets/motion.py", line 127, in plot_matplotlib
      q_95 = np.quantile(amps_abs, 0.95)
    File "/opt/conda/lib/python3.9/site-packages/numpy/lib/function_base.py", line 4543, in quantile
      return _quantile_unchecked(
    File "/opt/conda/lib/python3.9/site-packages/numpy/lib/function_base.py", line 4555, in _quantile_unchecked
      return _ureduce(a,
    File "/opt/conda/lib/python3.9/site-packages/numpy/lib/function_base.py", line 3823, in _ureduce
      r = func(a, **kwargs)
    File "/opt/conda/lib/python3.9/site-packages/numpy/lib/function_base.py", line 4722, in _quantile_ureduce_func
      result = _quantile(arr,
    File "/opt/conda/lib/python3.9/site-packages/numpy/lib/function_base.py", line 4831, in _quantile
      slices_having_nans = np.isnan(arr[-1, ...])
  IndexError: index -1 is out of bounds for axis 0 with size 0
...
```

**Comment by alejoe91** [comment]
@bjhardcastle fixed by https://github.com/AllenNeuralDynamics/aind-ephys-visualization/pull/4 and merged into main pipeline in CO
