### ISSUE TITLE
Error reading subject metadata for some sessions

### ISSUE THREAD

**Issue by bjhardcastle** [AllenNeuralDynamics/aind-ephys-pipeline-kilosort25#2]
Workflow exited with the following error:
``` 
N E X T F L O W  ~  version 22.10.0
Launching `main.nf` [comp-26c8af68-0b43-45ab-9d3d-32c5c25] DSL1 - revision: c8d71b5fa9
[05/1f9e57] Submitted process > capsule_nwb_packaging_subject_capsule_10 (capsule-1748641)
[5c/c481ad] Submitted process > capsule_aind_ephys_job_dispatch_4 (capsule-5089190)
Error executing process > 'capsule_nwb_packaging_subject_capsule_10 (capsule-1748641)'

Caused by:
  Essential container in task exited

Command executed:

  #!/usr/bin/env bash
  set -e
  
  export CO_CAPSULE_ID=dde17e00-2bad-4ceb-a00e-699ec25aca64
  export CO_CPUS=4
  export CO_MEMORY=34359738368
  
  mkdir -p capsule
  mkdir -p capsule/data && ln -s $PWD/capsule/data /data
  mkdir -p capsule/results && ln -s $PWD/capsule/results /results
  mkdir -p capsule/scratch && ln -s $PWD/capsule/scratch /scratch
  
  echo "[capsule-1748641] cloning git repo..."
  git clone "https://$GIT_ACCESS_TOKEN@codeocean.allenneuraldynamics.org/capsule-1748641.git" capsule-repo
  git -C capsule-repo checkout 9dc8a496f86fe38250d584b8e3d396581b7e404b --quiet
  mv capsule-repo/code capsule/code
  rm -rf capsule-repo
  
  echo "[capsule-1748641] running capsule..."
  cd capsule/code
  chmod +x run
  ./run
  
  echo "[capsule-1748641] completed!"

Command exit status:
  1

Command output:
  [capsule-1748641] cloning git repo...
  [capsule-1748641] running capsule...
  Backend: zarr
  Asset name: ecephys_626791_2022-08-17_00-00-00

Command error:
  [capsule-1748641] cloning git repo...
  Cloning into 'capsule-repo'...
  [capsule-1748641] running capsule...
  + python -u run_capsule.py
  Backend: zarr
  Asset name: ecephys_626791_2022-08-17_00-00-00
  Traceback (most recent call last):
    File "/tmp/nxf.ApkO7rHLYv/capsule/code/run_capsule.py", line 182, in <module>
      run()
    File "/tmp/nxf.ApkO7rHLYv/capsule/code/run_capsule.py", line 153, in run
      species=subject_metadata["species"]["name"],
  TypeError: string indices must be integers

Work dir:
  s3://codeocean-s3batchbucket-16itpvq060udk/1f8f159a-7670-47a9-baf1-078905fc9c2e/05/1f9e57cfc34ba211b0adf807a8637b

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`
```

I'm guessing this is a metadata schema issue, where `subject_metadata["species"]` is a str in older versions and a dict in newer versions.

**Comment by alejoe91** [comment]
Yep, fixed [here](https://github.com/AllenNeuralDynamics/NWB_Packaging_Subject_Capsule/commit/a1af634e47796d2bbebf78c2b88507df48f4df82). Can you try to rerun the session?

**Comment by bjhardcastle** [comment]
Thanks for the quick fix. Re-running now

**Comment by alejoe91** [comment]
Fixed
